insert into diary5 (title, description, date, weather) values ('テストタイトル', 'ひまさく最高だろjk', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('テストタイトル2', '[strong]あずにゃーん[/strong][small]ヤッテヤルデス[/small][image]http://livedoor.blogimg.jp/dqnplus/imgs/c/a/cab932ee.jpg[/image]', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('ほめらじ。', '[big]ほめられてのびるらじおPP[/big]', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('ゆるゆり', 'ひまさく最高だろjk[code]$non_displayables[] = "/%0[0-8bcef]/";[/code]', (select CURRENT_TIMESTAMP()), 10);
insert into diary5 (title, description, date, weather) values ('ゆる', 'ひまさく最高だろjk', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('ゆり', 'ひまさく最高だろjk2', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('マイペースで', 'ひまさく最高だろjk3', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('いきましょう', 'ひまさく最高だろjk4', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('ゆらららら', 'ひまさく最高だろjk5', (select CURRENT_TIMESTAMP()), 1);
insert into diary5 (title, description, date, weather) values ('だいじけーん', 'ひまさく最高だろjk6', (select CURRENT_TIMESTAMP()), 1);
insert into tag_master (name) values ('ひとりごと');
insert into tag_master (name) values ('アニメ');
insert into tag_master (name) values ('PCゲーム');
insert into tag (entry_id, tag_id) values (1, 1);
insert into tag (entry_id, tag_id) values (1, 2);
insert into tag (entry_id, tag_id) values (2, 1);
insert into tag (entry_id, tag_id) values (3, 2);
insert into tag (entry_id, tag_id) values (3, 3);
insert into tag (entry_id, tag_id) values (4, 3);
insert into tag (entry_id, tag_id) values (5, 3);
insert into tag (entry_id, tag_id) values (6, 3);
insert into tag (entry_id, tag_id) values (7, 3);
insert into tag (entry_id, tag_id) values (8, 3);
insert into tag (entry_id, tag_id) values (9, 3);
insert into tag (entry_id, tag_id) values (10, 3);
